server:
  port: 8080

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/sgu
    username: sgu_user
    password: sgu_pass
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: auth
        format_sql: false
    show-sql: false
  jackson:
    default-property-inclusion: non_null

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

sgu:
  jwt:
    secret: ${JWT_SECRET:c2d1LWRlbW8tc2VjcmV0LWtleS1jaGFuZ2UtbWUtaW4tcHJvZHVjdGlvbi1wbGVhc2UtMjU2Yml0cw==}
    access-token-expiration-minutes: 15
    refresh-token-expiration-days: 7
    issuer: sgu-auth-service

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    mx.edu.sgu.auth: INFO

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/sgu
    username: sgu_user
    password: sgu_pass
